# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84463b574d3882fc03f82148ad151e3dcbea4120c51ffb6bf23667b6f0191f8cbba1e0e152c61c82df6c9d6d246f38937575b4190fd8c97975c2b637d4b39b9c

test:
  secret_key_base: fd274e98fdba597a60634a2c1ef723e7019ec17d1c3dca619de59c76c49ef430fbde2231106e60551e0e6ce2056c0f6a59204bb47051c1aa98735c4e0ad1eada

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
